### ISSUE TITLE
adrenaline failed at start script when running locally

### ISSUE THREAD

**Issue by h-clickshift** [shobrook/adrenaline#31]
source branch: adrenaline-master
linux: Ubuntu 18.04.1 LTS
node: v10.13.0
npm 6.4.1
---------------
npm install 
-> is fine
---------------
npm start-local
->npm ERR! missing script: start-local
---------------
npm start 
->
SyntaxError: Unexpected token ;
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! adrenaline@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the adrenaline@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by geniusfoever** [comment]
Same error "npm ERR! missing script: start-local" here on windows, but npm start is ok

**Comment by shobrook** [comment]
Closed as this is now an issues-only repository.
